const NATIONAL_TEAMS = [
  "LAS VEGAS",
  "GOGOGOGO",
  "ANCONA",
  "SAN GIACOMO",
  "LAMEZIA TERME",
  "MEDELLIN",
  "TORONTO PAESE",
  "BOGOTÀ",
  "L'AQUILA",
  "VIA INDIPENDENZA",
  "VILLA MAISÉ",
  "SANTA PETRONILLA",
  "TRANI",
  "FROSINONE",
  "KAMBURUGAMUWA",
  "TROPEA",
  "CASACALENDA",
  "COLLESALVETTI",
  "CASAL THAULERO",
  "LIVORNO",
  "GODO",
  "PAPERINO",
  "SAN BENEDETTO IN PERILLIS",
  "CERCHIARA",
  "CHIETI SCALO",
  "CALIFOGGIA",
  "ISOLE COOK",
  "FICULLO",
  "CEPAGATTI",
  "ORGIA",
  "PAVIA",
  "THIMPHU",
  "CERIGNOLA",
  "LA VAGINA",
  "QUINTO ROMANO",
  "PIZZO CALABRO",
  "GARRUFO",
  "MARACAIBO",
  "PENNA SANT'ANDREA",
  "VIGONZA",
  "LUGANO",
  "BOLOGNA",
  "ALBA ADRIATICA",
  "MANDATORICCIO",
  "TERAMO OHANA",
  "ACAPULCO",
  "BELSEDERE",
  "VILLA POTENZA",
  "POGGIO UMBRICCHIO",
  "SANT'AGATA DEI GOTI",
  "COLOGNA CARICA",
  "SCOPPITO",
  "GNOCCA",
  "CHIAVARI",
  "RAMAZZANO LE PULCI 2",
  "TRONGSA",
  "ADDIS ABEBA",
  "OZZANO",
  "VOLTARROSTO",
  "TEAMPHU",
  "MOSCUFO",
  "GATČINA",
  "RAMAZZANO LE PULCI",
  "OTTAWA",
];

function normalizeNationalTeam(value) {
  return String(value || "").trim().toUpperCase();
}

function isValidNationalTeam(value) {
  return NATIONAL_TEAMS.includes(normalizeNationalTeam(value));
}

module.exports = {
  NATIONAL_TEAMS,
  normalizeNationalTeam,
  isValidNationalTeam,
};